import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

const seedQuestions = [
  // —— Qualifs (manche 1) ——
  {
    text: "Pour quels accords signés en 1925 Aristide Briand et Gustav Stresemann ont-ils reçu le Nobel de la paix ?",
    category: "NOBEL DE LA PAIX",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Les accords de Locarno",
    options: [
      "Les accords de Paris",
      "Les accords de Sèvres",
      "Les accords de Genève",
      "Les accords de Locarno",
    ],
    qualifSlot: 1,
  },
  {
    text: "Quel pays a remporté la Coupe du monde de football en 1998 ?",
    category: "SPORT",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "La France",
    options: ["Le Brésil", "L'Allemagne", "L'Italie", "La France"],
    qualifSlot: 2,
  },
  {
    text: "Quel animateur présentait « La Roue de la Fortune » sur TF1 dans les années 90 ?",
    category: "TÉLÉ 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Christophe Dechavanne",
    options: [
      "Arthur",
      "Christophe Dechavanne",
      "Patrick Sébastien",
      "Nagui",
    ],
    qualifSlot: 3,
  },
  {
    text: "Quel groupe américain sort l'album « Dookie » en 1994 ?",
    category: "MUSIQUE 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Green Day",
    options: ["Nirvana", "Green Day", "Offspring", "Blink-182"],
  },
  {
    text: "En 1998, quel buteur français marque deux têtes en finale de Coupe du monde ?",
    category: "SPORT 90s",
    round: "QUALIFS" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Zinédine Zidane",
    options: ["David Trezeguet", "Zinédine Zidane"],
    qualifSlot: 4,
  },
  {
    text: "Quelle émission de M6 mettait en scène des colocataires dès 2001 et a lancé la téléréalité en France ?",
    category: "TÉLÉ 2000s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Loft Story",
    options: ["Secret Story", "Loft Story", "Koh-Lanta", "Star Academy"],
    qualifSlot: 5,
  },
  {
    text: "Quel dessin animé japonais, diffusé sur TF1 dans Club Dorothée, met en scène Sangoku ?",
    category: "TÉLÉ 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Dragon Ball Z",
    options: ["Goldorak", "Dragon Ball Z", "Les Chevaliers du Zodiaque", "Candy"],
    qualifSlot: 6,
  },
  {
    text: "Quel film français de 2001, avec Audrey Tautou, se déroule à Montmartre ?",
    category: "CINÉMA 2000s",
    round: "QUALIFS" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Le Fabuleux Destin d'Amélie Poulain",
    options: ["Amélie Poulain", "Le Fabuleux Destin d'Amélie Poulain"],
    qualifSlot: 7,
  },
  {
    text: "Quel duo électro français sort « Around the World » en 1997 ?",
    category: "MUSIQUE 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Daft Punk",
    options: ["Cassius", "Daft Punk", "Air", "Modjo"],
    qualifSlot: 8,
  },
  {
    text: "Sur quelle chaîne française trouvait-on « Hélène et les Garçons » au début des années 90 ?",
    category: "TÉLÉ 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "TF1",
    options: ["France 2", "TF1", "M6", "Canal+"],
    qualifSlot: 9,
  },
  {
    text: "Quel jeu vidéo de capture de monstres cartonnés débarque en France en 1999 ?",
    category: "POP CULTURE 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Pokémon",
    options: ["Digimon", "Pokémon", "Yu-Gi-Oh!", "Tetris"],
    qualifSlot: 10,
  },
  {
    text: "Quelle marque de yaourt à la pub « C'est moi qui l'ai fait » ?",
    category: "PUB 90s",
    round: "QUALIFS" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Danone",
    options: ["Yoplait", "Danone", "Candia", "Mamie Nova"],
    qualifSlot: 11,
  },
  {
    text: "Quelle série policière française avec Commissaire Moulin était déjà un classique relu dans les 90s ?",
    category: "TÉLÉ 90s",
    round: "QUALIFS" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Navarro",
    options: ["Navarro", "Julie Lescaut"],
    qualifSlot: 12,
  },

  // —— Compet' (manche 2) — thème pop culture ——
  {
    text: "Quel film de 1993 avec Christian Clavier contient la réplique « Il est pas mort ! » ?",
    category: "CINÉMA 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Les Visiteurs",
    options: ["La Cité de la peur", "Les Visiteurs", "Astérix et Obélix", "Le Dîner de cons"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quelle émission de télé-crochet a révélé Jenifer en 2002 ?",
    category: "TÉLÉ 2000s",
    round: "COMPET" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Star Academy",
    options: ["Nouvelle Star", "Star Academy"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel présentateur animait « Questions pour un champion » sur France 3 pendant des décennies ?",
    category: "TÉLÉ 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Jean-Pierre Foucault",
    options: [
      "Benjamin Castaldi",
      "Jean-Pierre Foucault",
      "Laurent Romejko",
      "Cyril Féraud",
    ],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel groupe de rap sort « Suprême NTM » et « 1993… J'appuie sur l'accélérateur » ?",
    category: "MUSIQUE 90s",
    round: "COMPET" as const,
    answerMode: "DUO" as const,
    correctAnswer: "NTM",
    options: ["IAM", "NTM"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel commentateur français est surnommé la « Voix du football » sur TF1 dans les années 90 ?",
    category: "SPORT 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Thierry Roland",
    options: ["Thierry Roland", "Pierre Ménès", "Christophe Gourcuff", "Bixente Lizarazu"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quelle série américaine sur six amis à New York cartonne en France dès la fin des 90s ?",
    category: "TÉLÉ 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Friends",
    options: ["Seinfeld", "Friends", "Buffalo Bill", "Ally McBeal"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel film de Luc Besson de 1997 met en scène Leeloo et un taxi dans le futur ?",
    category: "CINÉMA 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Le Cinquième Élément",
    options: ["Nikita", "Le Cinquième Élément", "Léon", "Arthur et les Minimoys"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel réseau français, avant Internet grand public, permettait les numéros « 36 15 » ?",
    category: "PUB & MÉDIAS",
    round: "COMPET" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Le Minitel",
    options: ["Le Minitel", "Arcom"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel chanteur sort « Je danse le Mia » en 1994 ?",
    category: "MUSIQUE 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "IAM",
    options: ["MC Solaar", "IAM", "Doc Gynéco", "Sinik"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quelle émission de PAF des années 90 réunissait les Musclés et Dorothée ?",
    category: "TÉLÉ 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Club Dorothée",
    options: ["Récré A2", "Club Dorothée", "C'est pas sorcier", "Jacky"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel film de Mathieu Kassovitz, sorti en 1995, se déroule dans les banlieues de Marseille ?",
    category: "CINÉMA 90s",
    round: "COMPET" as const,
    answerMode: "DUO" as const,
    correctAnswer: "La Haine",
    options: ["La Haine", "Roméo + Juliette"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel parc d'attractions ouvre près de Paris en 1992 (repère des sorties scolaires des 90s) ?",
    category: "POP CULTURE 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Disneyland Paris",
    options: [
      "Parc Astérix",
      "Disneyland Paris",
      "Futuroscope",
      "Walibi",
    ],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quelle marque de yaourt à la pub « C'est moi qui l'ai fait » cartonnait dans les pubs des 90s ?",
    category: "PUB & MÉDIAS",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Danone (Danonino)",
    options: ["Yoplait", "Danone (Danonino)", "Candia", "Mamie Nova"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel réalisateur français tourne « Le Grand Bleu » en 1988, culte sur les câbles des 90s ?",
    category: "CINÉMA 90s",
    round: "COMPET" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Luc Besson",
    options: ["Jean-Jacques Annaud", "Luc Besson"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel jeu télévisé de France 2 avec des lettres et des chiffres existait déjà dans les 90s (version actuelle depuis 2006) ?",
    category: "TÉLÉ 2000s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Des chiffres et des lettres",
    options: [
      "Motus",
      "Des chiffres et des lettres",
      "Tout le monde veut prendre sa place",
      "Slam",
    ],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel groupe sort « Désenchantée » en 1991 ?",
    category: "MUSIQUE 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Mylène Farmer",
    options: ["Céline Dion", "Mylène Farmer", "Lara Fabian", "Patricia Kaas"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quelle émission d'aventuriers sur une île arrive sur TF1 en 2001 ?",
    category: "TÉLÉ 2000s",
    round: "COMPET" as const,
    answerMode: "CASH" as const,
    correctAnswer: "Koh-Lanta",
    options: [],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel film de 2006 avec Jamel Debbouze et Omar Sy s'appelle « Nos jours heureux » ?",
    category: "CINÉMA 2000s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Nos jours heureux",
    options: [
      "Nos jours heureux",
      "Le Brio",
      "Les Trois Frères",
      "Le Prénom",
    ],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel tube de 2000 de Modjo sample « Rhythm of the Night » ?",
    category: "MUSIQUE 2000s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Lady (Hear Me Tonight)",
    options: ["Lady (Hear Me Tonight)", "One More Time", "Alizée", "Lola"],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel dessin animé « Il était une fois… » expliquait l'histoire aux gamins des 90s ?",
    category: "TÉLÉ 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Il était une fois… l'Homme",
    options: [
      "Il était une fois… l'Homme",
      "Candy",
      "Captain Tsubasa",
      "Albator",
    ],
    theme: "Pop culture 90-2000",
  },
  {
    text: "Quel film du Splendid, sorti en 1979, se passe aux sports d'hiver ?",
    category: "CINÉMA 90s",
    round: "COMPET" as const,
    answerMode: "CARRE" as const,
    correctAnswer: "Les Bronzés font du ski",
    options: [
      "Le Père Noël est une ordure",
      "Les Bronzés font du ski",
      "La Boum",
      "L'Opération Corned-Beef",
    ],
    theme: "Pop culture 90-2000",
  },

  // —— Finale ——
  {
    text: "Quelle est la capitale de l'Australie ?",
    category: "GÉOGRAPHIE",
    round: "FINALE" as const,
    answerMode: "DUO" as const,
    correctAnswer: "Canberra",
    options: ["Sydney", "Canberra"],
    theme: "Capitales",
  },
  {
    text: "En quelle année a eu lieu la Révolution française ?",
    category: "HISTOIRE",
    round: "FINALE" as const,
    answerMode: "CASH" as const,
    correctAnswer: "1789",
    options: [],
  },
  {
    text: "En quelle année la France remporte sa deuxième Coupe du monde (après 1998) ?",
    category: "SPORT 2000s",
    round: "FINALE" as const,
    answerMode: "CASH" as const,
    correctAnswer: "2018",
    options: [],
  },
  {
    text: "Quel est le prénom du héros de « Titanic » joué par Leonardo DiCaprio ?",
    category: "CINÉMA 90s",
    round: "FINALE" as const,
    answerMode: "CASH" as const,
    correctAnswer: "Jack",
    options: [],
  },
  {
    text: "Combien de saisons compte la série « Kaamelott » (première diffusion 2005) ?",
    category: "TÉLÉ 2000s",
    round: "FINALE" as const,
    answerMode: "CASH" as const,
    correctAnswer: "6",
    options: [],
    notes: "6 livres / saisons principales.",
  },
  {
    text: "Quel opérateur lance l'iPhone en France en 2007 ?",
    category: "POP CULTURE 2000s",
    round: "FINALE" as const,
    answerMode: "CASH" as const,
    correctAnswer: "Orange",
    options: [],
  },
  {
    text: "« Les Deschiens » sont diffusés à l'origine sur quelle chaîne ?",
    category: "TÉLÉ 90s",
    round: "FINALE" as const,
    answerMode: "CASH" as const,
    correctAnswer: "Canal+",
    options: [],
  },
];

async function main() {
  await prisma.question.deleteMany();

  await prisma.question.createMany({
    data: seedQuestions.map(({ notes, ...q }) => ({
      ...q,
      notes: notes ?? null,
    })),
  });

  console.log(`✓ ${seedQuestions.length} questions créées (pop culture 90-2000 + classiques)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
